const TIMEZONE_DATA = [
  // North America
  { city: "New York", country: "United States", region: "North America", timezone: "America/New_York", keywords: ["New York State", "NY", "EST", "EDT", "Manhattan", "Brooklyn", "Queens"] },
  { city: "Los Angeles", country: "United States", region: "North America", timezone: "America/Los_Angeles", keywords: ["California", "CA", "PST", "PDT", "Hollywood", "LA"] },
  { city: "Chicago", country: "United States", region: "North America", timezone: "America/Chicago", keywords: ["Illinois", "IL", "CST", "CDT", "Midwest"] },
  { city: "Denver", country: "United States", region: "North America", timezone: "America/Denver", keywords: ["Colorado", "CO", "MST", "MDT", "Mountain Time"] },
  { city: "Phoenix", country: "United States", region: "North America", timezone: "America/Phoenix", keywords: ["Arizona", "AZ", "MST"] },
  { city: "Anchorage", country: "United States", region: "North America", timezone: "America/Anchorage", keywords: ["Alaska", "AK", "AKST", "AKDT"] },
  { city: "Honolulu", country: "United States", region: "North America", timezone: "Pacific/Honolulu", keywords: ["Hawaii", "HI", "HST", "Oahu"] },
  { city: "Toronto", country: "Canada", region: "North America", timezone: "America/Toronto", keywords: ["Ontario", "ON", "EST", "EDT"] },
  { city: "Vancouver", country: "Canada", region: "North America", timezone: "America/Vancouver", keywords: ["British Columbia", "BC", "PST", "PDT"] },
  { city: "Edmonton", country: "Canada", region: "North America", timezone: "America/Edmonton", keywords: ["Alberta", "AB", "MST", "MDT"] },
  { city: "Mexico City", country: "Mexico", region: "North America", timezone: "America/Mexico_City", keywords: ["CDMX", "CST", "CDT", "Ciudad de México"] },

  // Central America
  { city: "Guatemala City", country: "Guatemala", region: "Central America", timezone: "America/Guatemala", keywords: ["CST", "Guate"] },
  { city: "Belmopan", country: "Belize", region: "Central America", timezone: "America/Belize", keywords: ["CST"] },
  { city: "Tegucigalpa", country: "Honduras", region: "Central America", timezone: "America/Tegucigalpa", keywords: ["CST"] },
  { city: "San Salvador", country: "El Salvador", region: "Central America", timezone: "America/El_Salvador", keywords: ["CST"] },
  { city: "Managua", country: "Nicaragua", region: "Central America", timezone: "America/Managua", keywords: ["CST"] },
  { city: "San José", country: "Costa Rica", region: "Central America", timezone: "America/Costa_Rica", keywords: ["CST", "San Jose"] },
  { city: "Panama City", country: "Panama", region: "Central America", timezone: "America/Panama", keywords: ["EST"] },

  // Caribbean
  { city: "Havana", country: "Cuba", region: "Caribbean", timezone: "America/Havana", keywords: ["CST", "CDT", "La Habana"] },
  { city: "Kingston", country: "Jamaica", region: "Caribbean", timezone: "America/Jamaica", keywords: ["EST"] },
  { city: "Port-au-Prince", country: "Haiti", region: "Caribbean", timezone: "America/Port-au-Prince", keywords: ["EST", "EDT"] },
  { city: "Santo Domingo", country: "Dominican Republic", region: "Caribbean", timezone: "America/Santo_Domingo", keywords: ["AST"] },
  { city: "San Juan", country: "Puerto Rico", region: "Caribbean", timezone: "America/Puerto_Rico", keywords: ["AST", "PR"] },
  { city: "Nassau", country: "Bahamas", region: "Caribbean", timezone: "America/Nassau", keywords: ["EST", "EDT"] },
  { city: "Port of Spain", country: "Trinidad and Tobago", region: "Caribbean", timezone: "America/Port_of_Spain", keywords: ["AST"] },
  { city: "Bridgetown", country: "Barbados", region: "Caribbean", timezone: "America/Barbados", keywords: ["AST"] },
  { city: "St. George's", country: "Grenada", region: "Caribbean", timezone: "America/Grenada", keywords: ["AST"] },
  { city: "Castries", country: "Saint Lucia", region: "Caribbean", timezone: "America/St_Lucia", keywords: ["AST"] },
  { city: "Kingstown", country: "Saint Vincent and the Grenadines", region: "Caribbean", timezone: "America/St_Vincent", keywords: ["AST"] },
  { city: "St. John's", country: "Antigua and Barbuda", region: "Caribbean", timezone: "America/Antigua", keywords: ["AST"] },
  { city: "Roseau", country: "Dominica", region: "Caribbean", timezone: "America/Dominica", keywords: ["AST"] },
  { city: "Basseterre", country: "Saint Kitts and Nevis", region: "Caribbean", timezone: "America/St_Kitts", keywords: ["AST"] },

  // South America
  { city: "São Paulo", country: "Brazil", region: "South America", timezone: "America/Sao_Paulo", keywords: ["BRT", "SP", "Sao Paulo"] },
  { city: "Buenos Aires", country: "Argentina", region: "South America", timezone: "America/Argentina/Buenos_Aires", keywords: ["ART", "BA", "CABA"] },
  { city: "Santiago", country: "Chile", region: "South America", timezone: "America/Santiago", keywords: ["CLT", "CLST"] },
  { city: "Lima", country: "Peru", region: "South America", timezone: "America/Lima", keywords: ["PET"] },
  { city: "Bogotá", country: "Colombia", region: "South America", timezone: "America/Bogota", keywords: ["COT", "Bogota"] },
  { city: "Caracas", country: "Venezuela", region: "South America", timezone: "America/Caracas", keywords: ["VET"] },
  { city: "Quito", country: "Ecuador", region: "South America", timezone: "America/Guayaquil", keywords: ["ECT", "Ecuador Time"] },
  { city: "La Paz", country: "Bolivia", region: "South America", timezone: "America/La_Paz", keywords: ["BOT"] },
  { city: "Asunción", country: "Paraguay", region: "South America", timezone: "America/Asuncion", keywords: ["PYT", "PYST", "Asuncion"] },
  { city: "Montevideo", country: "Uruguay", region: "South America", timezone: "America/Montevideo", keywords: ["UYT"] },
  { city: "Georgetown", country: "Guyana", region: "South America", timezone: "America/Guyana", keywords: ["GYT"] },
  { city: "Paramaribo", country: "Suriname", region: "South America", timezone: "America/Paramaribo", keywords: ["SRT"] },

  // Europe
  { city: "London", country: "United Kingdom", region: "Europe", timezone: "Europe/London", keywords: ["England", "UK", "GMT", "BST", "Great Britain"] },
  { city: "Paris", country: "France", region: "Europe", timezone: "Europe/Paris", keywords: ["CET", "CEST", "Île-de-France"] },
  { city: "Berlin", country: "Germany", region: "Europe", timezone: "Europe/Berlin", keywords: ["CET", "CEST", "Deutschland"] },
  { city: "Madrid", country: "Spain", region: "Europe", timezone: "Europe/Madrid", keywords: ["CET", "CEST", "España"] },
  { city: "Rome", country: "Italy", region: "Europe", timezone: "Europe/Rome", keywords: ["CET", "CEST", "Roma", "Italia"] },
  { city: "Amsterdam", country: "Netherlands", region: "Europe", timezone: "Europe/Amsterdam", keywords: ["CET", "CEST", "Holland", "Noord-Holland"] },
  { city: "Brussels", country: "Belgium", region: "Europe", timezone: "Europe/Brussels", keywords: ["CET", "CEST", "Bruxelles"] },
  { city: "Zurich", country: "Switzerland", region: "Europe", timezone: "Europe/Zurich", keywords: ["CET", "CEST", "Zürich"] },
  { city: "Vienna", country: "Austria", region: "Europe", timezone: "Europe/Vienna", keywords: ["CET", "CEST", "Wien", "Österreich"] },
  { city: "Stockholm", country: "Sweden", region: "Europe", timezone: "Europe/Stockholm", keywords: ["CET", "CEST", "Sverige"] },
  { city: "Oslo", country: "Norway", region: "Europe", timezone: "Europe/Oslo", keywords: ["CET", "CEST", "Norge"] },
  { city: "Copenhagen", country: "Denmark", region: "Europe", timezone: "Europe/Copenhagen", keywords: ["CET", "CEST", "København", "Danmark"] },
  { city: "Helsinki", country: "Finland", region: "Europe", timezone: "Europe/Helsinki", keywords: ["EET", "EEST", "Suomi"] },
  { city: "Warsaw", country: "Poland", region: "Europe", timezone: "Europe/Warsaw", keywords: ["CET", "CEST", "Warszawa", "Polska"] },
  { city: "Prague", country: "Czech Republic", region: "Europe", timezone: "Europe/Prague", keywords: ["CET", "CEST", "Praha", "Czechia"] },
  { city: "Budapest", country: "Hungary", region: "Europe", timezone: "Europe/Budapest", keywords: ["CET", "CEST", "Magyarország"] },
  { city: "Bucharest", country: "Romania", region: "Europe", timezone: "Europe/Bucharest", keywords: ["EET", "EEST", "București"] },
  { city: "Athens", country: "Greece", region: "Europe", timezone: "Europe/Athens", keywords: ["EET", "EEST", "Athína", "Hellas"] },
  { city: "Lisbon", country: "Portugal", region: "Europe", timezone: "Europe/Lisbon", keywords: ["WET", "WEST", "Lisboa"] },
  { city: "Dublin", country: "Ireland", region: "Europe", timezone: "Europe/Dublin", keywords: ["GMT", "IST", "Éire"] },
  { city: "Reykjavik", country: "Iceland", region: "Europe", timezone: "Atlantic/Reykjavik", keywords: ["GMT", "Reykjavík"] },
  { city: "Moscow", country: "Russia", region: "Europe", timezone: "Europe/Moscow", keywords: ["MSK", "Moskva"] },
  { city: "Istanbul", country: "Turkey", region: "Europe", timezone: "Europe/Istanbul", keywords: ["TRT", "Constantinople", "Türkiye"] },
  { city: "Kyiv", country: "Ukraine", region: "Europe", timezone: "Europe/Kyiv", keywords: ["EET", "EEST", "Kiev"] },
  { city: "Belgrade", country: "Serbia", region: "Europe", timezone: "Europe/Belgrade", keywords: ["CET", "CEST", "Beograd", "Srbija"] },
  { city: "Vilnius", country: "Lithuania", region: "Europe", timezone: "Europe/Vilnius", keywords: ["EET", "EEST", "Lietuva"] },
  { city: "Riga", country: "Latvia", region: "Europe", timezone: "Europe/Riga", keywords: ["EET", "EEST", "Latvija"] },
  { city: "Tallinn", country: "Estonia", region: "Europe", timezone: "Europe/Tallinn", keywords: ["EET", "EEST", "Eesti"] },
  { city: "Bratislava", country: "Slovakia", region: "Europe", timezone: "Europe/Bratislava", keywords: ["CET", "CEST", "Slovensko"] },
  { city: "Ljubljana", country: "Slovenia", region: "Europe", timezone: "Europe/Ljubljana", keywords: ["CET", "CEST", "Slovenija"] },
  { city: "Zagreb", country: "Croatia", region: "Europe", timezone: "Europe/Zagreb", keywords: ["CET", "CEST", "Hrvatska"] },
  { city: "Sarajevo", country: "Bosnia and Herzegovina", region: "Europe", timezone: "Europe/Sarajevo", keywords: ["CET", "CEST", "BiH"] },
  { city: "Podgorica", country: "Montenegro", region: "Europe", timezone: "Europe/Podgorica", keywords: ["CET", "CEST", "Crna Gora"] },
  { city: "Skopje", country: "North Macedonia", region: "Europe", timezone: "Europe/Skopje", keywords: ["CET", "CEST", "Makedonija"] },
  { city: "Tirana", country: "Albania", region: "Europe", timezone: "Europe/Tirane", keywords: ["CET", "CEST", "Shqipëri"] },
  { city: "Sofia", country: "Bulgaria", region: "Europe", timezone: "Europe/Sofia", keywords: ["EET", "EEST", "България"] },
  { city: "Chișinău", country: "Moldova", region: "Europe", timezone: "Europe/Chisinau", keywords: ["EET", "EEST", "Kishinev", "Chisinau"] },
  { city: "Minsk", country: "Belarus", region: "Europe", timezone: "Europe/Minsk", keywords: ["MSK", "Беларусь"] },
  { city: "Luxembourg", country: "Luxembourg", region: "Europe", timezone: "Europe/Luxembourg", keywords: ["CET", "CEST", "Lëtzebuerg"] },
  { city: "Valletta", country: "Malta", region: "Europe", timezone: "Europe/Malta", keywords: ["CET", "CEST"] },
  { city: "Nicosia", country: "Cyprus", region: "Europe", timezone: "Asia/Nicosia", keywords: ["EET", "EEST", "Lefkosia"] },
  { city: "Monaco", country: "Monaco", region: "Europe", timezone: "Europe/Monaco", keywords: ["CET", "CEST"] },
  { city: "Vaduz", country: "Liechtenstein", region: "Europe", timezone: "Europe/Vaduz", keywords: ["CET", "CEST"] },
  { city: "San Marino", country: "San Marino", region: "Europe", timezone: "Europe/San_Marino", keywords: ["CET", "CEST"] },
  { city: "Andorra la Vella", country: "Andorra", region: "Europe", timezone: "Europe/Andorra", keywords: ["CET", "CEST"] },
  { city: "Pristina", country: "Kosovo", region: "Europe", timezone: "Europe/Belgrade", keywords: ["CET", "CEST", "Prishtinë"] },

  // Africa
  { city: "Cairo", country: "Egypt", region: "Africa", timezone: "Africa/Cairo", keywords: ["EET", "Al-Qahira"] },
  { city: "Lagos", country: "Nigeria", region: "Africa", timezone: "Africa/Lagos", keywords: ["WAT", "West Africa"] },
  { city: "Johannesburg", country: "South Africa", region: "Africa", timezone: "Africa/Johannesburg", keywords: ["SAST", "Joburg", "Gauteng"] },
  { city: "Nairobi", country: "Kenya", region: "Africa", timezone: "Africa/Nairobi", keywords: ["EAT", "East Africa"] },
  { city: "Casablanca", country: "Morocco", region: "Africa", timezone: "Africa/Casablanca", keywords: ["WET", "WEST", "Dar el Beida"] },
  { city: "Accra", country: "Ghana", region: "Africa", timezone: "Africa/Accra", keywords: ["GMT"] },
  { city: "Addis Ababa", country: "Ethiopia", region: "Africa", timezone: "Africa/Addis_Ababa", keywords: ["EAT"] },
  { city: "Dar es Salaam", country: "Tanzania", region: "Africa", timezone: "Africa/Dar_es_Salaam", keywords: ["EAT"] },
  { city: "Tunis", country: "Tunisia", region: "Africa", timezone: "Africa/Tunis", keywords: ["CET"] },
  { city: "Algiers", country: "Algeria", region: "Africa", timezone: "Africa/Algiers", keywords: ["CET", "Alger"] },
  { city: "Luanda", country: "Angola", region: "Africa", timezone: "Africa/Luanda", keywords: ["WAT"] },
  { city: "Porto-Novo", country: "Benin", region: "Africa", timezone: "Africa/Porto-Novo", keywords: ["WAT"] },
  { city: "Gaborone", country: "Botswana", region: "Africa", timezone: "Africa/Gaborone", keywords: ["CAT"] },
  { city: "Ouagadougou", country: "Burkina Faso", region: "Africa", timezone: "Africa/Ouagadougou", keywords: ["GMT"] },
  { city: "Bujumbura", country: "Burundi", region: "Africa", timezone: "Africa/Bujumbura", keywords: ["CAT"] },
  { city: "Yaoundé", country: "Cameroon", region: "Africa", timezone: "Africa/Douala", keywords: ["WAT", "Yaounde"] },
  { city: "Bangui", country: "Central African Republic", region: "Africa", timezone: "Africa/Bangui", keywords: ["WAT", "CAR"] },
  { city: "N'Djamena", country: "Chad", region: "Africa", timezone: "Africa/Ndjamena", keywords: ["WAT"] },
  { city: "Moroni", country: "Comoros", region: "Africa", timezone: "Indian/Comoro", keywords: ["EAT"] },
  { city: "Kinshasa", country: "Democratic Republic of the Congo", region: "Africa", timezone: "Africa/Kinshasa", keywords: ["WAT", "DRC", "Congo-Kinshasa"] },
  { city: "Brazzaville", country: "Republic of the Congo", region: "Africa", timezone: "Africa/Brazzaville", keywords: ["WAT", "Congo-Brazzaville"] },
  { city: "Abidjan", country: "Côte d'Ivoire", region: "Africa", timezone: "Africa/Abidjan", keywords: ["GMT", "Ivory Coast"] },
  { city: "Djibouti", country: "Djibouti", region: "Africa", timezone: "Africa/Djibouti", keywords: ["EAT"] },
  { city: "Malabo", country: "Equatorial Guinea", region: "Africa", timezone: "Africa/Malabo", keywords: ["WAT"] },
  { city: "Asmara", country: "Eritrea", region: "Africa", timezone: "Africa/Asmara", keywords: ["EAT"] },
  { city: "Mbabane", country: "Eswatini", region: "Africa", timezone: "Africa/Mbabane", keywords: ["SAST", "Swaziland"] },
  { city: "Libreville", country: "Gabon", region: "Africa", timezone: "Africa/Libreville", keywords: ["WAT"] },
  { city: "Banjul", country: "Gambia", region: "Africa", timezone: "Africa/Banjul", keywords: ["GMT"] },
  { city: "Conakry", country: "Guinea", region: "Africa", timezone: "Africa/Conakry", keywords: ["GMT"] },
  { city: "Bissau", country: "Guinea-Bissau", region: "Africa", timezone: "Africa/Bissau", keywords: ["GMT"] },
  { city: "Maseru", country: "Lesotho", region: "Africa", timezone: "Africa/Maseru", keywords: ["SAST"] },
  { city: "Monrovia", country: "Liberia", region: "Africa", timezone: "Africa/Monrovia", keywords: ["GMT"] },
  { city: "Tripoli", country: "Libya", region: "Africa", timezone: "Africa/Tripoli", keywords: ["EET", "Tarabulus"] },
  { city: "Antananarivo", country: "Madagascar", region: "Africa", timezone: "Indian/Antananarivo", keywords: ["EAT", "Tana"] },
  { city: "Lilongwe", country: "Malawi", region: "Africa", timezone: "Africa/Blantyre", keywords: ["CAT"] },
  { city: "Bamako", country: "Mali", region: "Africa", timezone: "Africa/Bamako", keywords: ["GMT"] },
  { city: "Nouakchott", country: "Mauritania", region: "Africa", timezone: "Africa/Nouakchott", keywords: ["GMT"] },
  { city: "Port Louis", country: "Mauritius", region: "Africa", timezone: "Indian/Mauritius", keywords: ["MUT"] },
  { city: "Maputo", country: "Mozambique", region: "Africa", timezone: "Africa/Maputo", keywords: ["CAT"] },
  { city: "Windhoek", country: "Namibia", region: "Africa", timezone: "Africa/Windhoek", keywords: ["CAT"] },
  { city: "Niamey", country: "Niger", region: "Africa", timezone: "Africa/Niamey", keywords: ["WAT"] },
  { city: "Kigali", country: "Rwanda", region: "Africa", timezone: "Africa/Kigali", keywords: ["CAT"] },
  { city: "São Tomé", country: "São Tomé and Príncipe", region: "Africa", timezone: "Africa/Sao_Tome", keywords: ["GMT", "Sao Tome"] },
  { city: "Dakar", country: "Senegal", region: "Africa", timezone: "Africa/Dakar", keywords: ["GMT"] },
  { city: "Victoria", country: "Seychelles", region: "Africa", timezone: "Indian/Mahe", keywords: ["SCT"] },
  { city: "Freetown", country: "Sierra Leone", region: "Africa", timezone: "Africa/Freetown", keywords: ["GMT"] },
  { city: "Mogadishu", country: "Somalia", region: "Africa", timezone: "Africa/Mogadishu", keywords: ["EAT", "Muqdisho"] },
  { city: "Juba", country: "South Sudan", region: "Africa", timezone: "Africa/Juba", keywords: ["CAT"] },
  { city: "Khartoum", country: "Sudan", region: "Africa", timezone: "Africa/Khartoum", keywords: ["CAT"] },
  { city: "Lomé", country: "Togo", region: "Africa", timezone: "Africa/Lome", keywords: ["GMT", "Lome"] },
  { city: "Kampala", country: "Uganda", region: "Africa", timezone: "Africa/Kampala", keywords: ["EAT"] },
  { city: "Lusaka", country: "Zambia", region: "Africa", timezone: "Africa/Lusaka", keywords: ["CAT"] },
  { city: "Harare", country: "Zimbabwe", region: "Africa", timezone: "Africa/Harare", keywords: ["CAT"] },

  // Middle East
  { city: "Dubai", country: "United Arab Emirates", region: "Middle East", timezone: "Asia/Dubai", keywords: ["GST", "UAE", "Emirates"] },
  { city: "Riyadh", country: "Saudi Arabia", region: "Middle East", timezone: "Asia/Riyadh", keywords: ["AST", "KSA"] },
  { city: "Doha", country: "Qatar", region: "Middle East", timezone: "Asia/Qatar", keywords: ["AST"] },
  { city: "Kuwait City", country: "Kuwait", region: "Middle East", timezone: "Asia/Kuwait", keywords: ["AST"] },
  { city: "Tehran", country: "Iran", region: "Middle East", timezone: "Asia/Tehran", keywords: ["IRST", "IRDT", "Persia"] },
  { city: "Baghdad", country: "Iraq", region: "Middle East", timezone: "Asia/Baghdad", keywords: ["AST"] },
  { city: "Jerusalem", country: "Israel", region: "Middle East", timezone: "Asia/Jerusalem", keywords: ["IST", "IDT", "Tel Aviv"] },
  { city: "Beirut", country: "Lebanon", region: "Middle East", timezone: "Asia/Beirut", keywords: ["EET", "EEST"] },
  { city: "Amman", country: "Jordan", region: "Middle East", timezone: "Asia/Amman", keywords: ["EET", "EEST"] },
  { city: "Muscat", country: "Oman", region: "Middle East", timezone: "Asia/Muscat", keywords: ["GST"] },
  { city: "Damascus", country: "Syria", region: "Middle East", timezone: "Asia/Damascus", keywords: ["EET", "EEST", "Dimashq"] },
  { city: "Sana'a", country: "Yemen", region: "Middle East", timezone: "Asia/Aden", keywords: ["AST", "Sanaa"] },
  { city: "Manama", country: "Bahrain", region: "Middle East", timezone: "Asia/Bahrain", keywords: ["AST"] },
  { city: "Ramallah", country: "Palestine", region: "Middle East", timezone: "Asia/Hebron", keywords: ["EET", "EEST", "Gaza", "West Bank"] },

  // South Asia
  { city: "Mumbai", country: "India", region: "South Asia", timezone: "Asia/Kolkata", keywords: ["IST", "Bombay", "Maharashtra", "MH"] },
  { city: "Delhi", country: "India", region: "South Asia", timezone: "Asia/Kolkata", keywords: ["IST", "New Delhi", "NCR"] },
  { city: "Kolkata", country: "India", region: "South Asia", timezone: "Asia/Kolkata", keywords: ["IST", "Calcutta", "West Bengal", "WB"] },
  { city: "Bangalore", country: "India", region: "South Asia", timezone: "Asia/Kolkata", keywords: ["IST", "Bengaluru", "Karnataka", "KA"] },
  { city: "Karachi", country: "Pakistan", region: "South Asia", timezone: "Asia/Karachi", keywords: ["PKT", "Sindh"] },
  { city: "Dhaka", country: "Bangladesh", region: "South Asia", timezone: "Asia/Dhaka", keywords: ["BST", "Dacca"] },
  { city: "Colombo", country: "Sri Lanka", region: "South Asia", timezone: "Asia/Colombo", keywords: ["SLST"] },
  { city: "Kathmandu", country: "Nepal", region: "South Asia", timezone: "Asia/Kathmandu", keywords: ["NPT", "Katmandu"] },
  { city: "Kabul", country: "Afghanistan", region: "South Asia", timezone: "Asia/Kabul", keywords: ["AFT"] },
  { city: "Thimphu", country: "Bhutan", region: "South Asia", timezone: "Asia/Thimphu", keywords: ["BTT"] },
  { city: "Malé", country: "Maldives", region: "South Asia", timezone: "Indian/Maldives", keywords: ["MVT", "Male"] },

  // East Asia
  { city: "Tokyo", country: "Japan", region: "East Asia", timezone: "Asia/Tokyo", keywords: ["JST", "Kanto"] },
  { city: "Shanghai", country: "China", region: "East Asia", timezone: "Asia/Shanghai", keywords: ["CST", "CT"] },
  { city: "Beijing", country: "China", region: "East Asia", timezone: "Asia/Shanghai", keywords: ["CST", "CT", "Peking"] },
  { city: "Hong Kong", country: "China", region: "East Asia", timezone: "Asia/Hong_Kong", keywords: ["HKT", "HK"] },
  { city: "Seoul", country: "South Korea", region: "East Asia", timezone: "Asia/Seoul", keywords: ["KST", "Korea"] },
  { city: "Taipei", country: "Taiwan", region: "East Asia", timezone: "Asia/Taipei", keywords: ["CST", "TW"] },
  { city: "Ulaanbaatar", country: "Mongolia", region: "East Asia", timezone: "Asia/Ulaanbaatar", keywords: ["ULAT", "Ulan Bator"] },
  { city: "Pyongyang", country: "North Korea", region: "East Asia", timezone: "Asia/Pyongyang", keywords: ["KST", "DPRK"] },

  // Southeast Asia
  { city: "Singapore", country: "Singapore", region: "Southeast Asia", timezone: "Asia/Singapore", keywords: ["SGT", "SG"] },
  { city: "Bangkok", country: "Thailand", region: "Southeast Asia", timezone: "Asia/Bangkok", keywords: ["ICT", "Krung Thep"] },
  { city: "Jakarta", country: "Indonesia", region: "Southeast Asia", timezone: "Asia/Jakarta", keywords: ["WIB", "Java"] },
  { city: "Kuala Lumpur", country: "Malaysia", region: "Southeast Asia", timezone: "Asia/Kuala_Lumpur", keywords: ["MYT", "KL"] },
  { city: "Manila", country: "Philippines", region: "Southeast Asia", timezone: "Asia/Manila", keywords: ["PHT", "PH"] },
  { city: "Ho Chi Minh City", country: "Vietnam", region: "Southeast Asia", timezone: "Asia/Ho_Chi_Minh", keywords: ["ICT", "Saigon", "HCMC"] },
  { city: "Yangon", country: "Myanmar", region: "Southeast Asia", timezone: "Asia/Yangon", keywords: ["MMT", "Rangoon", "Burma"] },
  { city: "Phnom Penh", country: "Cambodia", region: "Southeast Asia", timezone: "Asia/Phnom_Penh", keywords: ["ICT"] },
  { city: "Vientiane", country: "Laos", region: "Southeast Asia", timezone: "Asia/Vientiane", keywords: ["ICT"] },
  { city: "Bandar Seri Begawan", country: "Brunei", region: "Southeast Asia", timezone: "Asia/Brunei", keywords: ["BNT"] },
  { city: "Dili", country: "Timor-Leste", region: "Southeast Asia", timezone: "Asia/Dili", keywords: ["TLT", "East Timor"] },

  // Central Asia
  { city: "Almaty", country: "Kazakhstan", region: "Central Asia", timezone: "Asia/Almaty", keywords: ["ALMT", "Alma-Ata"] },
  { city: "Tashkent", country: "Uzbekistan", region: "Central Asia", timezone: "Asia/Tashkent", keywords: ["UZT"] },
  { city: "Tbilisi", country: "Georgia", region: "Central Asia", timezone: "Asia/Tbilisi", keywords: ["GET"] },
  { city: "Baku", country: "Azerbaijan", region: "Central Asia", timezone: "Asia/Baku", keywords: ["AZT"] },
  { city: "Yerevan", country: "Armenia", region: "Central Asia", timezone: "Asia/Yerevan", keywords: ["AMT"] },
  { city: "Ashgabat", country: "Turkmenistan", region: "Central Asia", timezone: "Asia/Ashgabat", keywords: ["TMT"] },
  { city: "Dushanbe", country: "Tajikistan", region: "Central Asia", timezone: "Asia/Dushanbe", keywords: ["TJT"] },
  { city: "Bishkek", country: "Kyrgyzstan", region: "Central Asia", timezone: "Asia/Bishkek", keywords: ["KGT"] },

  // Russia
  { city: "Novosibirsk", country: "Russia", region: "Asia", timezone: "Asia/Novosibirsk", keywords: ["NOVT", "Siberia"] },
  { city: "Yekaterinburg", country: "Russia", region: "Asia", timezone: "Asia/Yekaterinburg", keywords: ["YEKT", "Urals"] },
  { city: "Vladivostok", country: "Russia", region: "Asia", timezone: "Asia/Vladivostok", keywords: ["VLAT", "Far East Russia"] },

  // Oceania
  { city: "Sydney", country: "Australia", region: "Oceania", timezone: "Australia/Sydney", keywords: ["AEST", "AEDT", "New South Wales", "NSW"] },
  { city: "Melbourne", country: "Australia", region: "Oceania", timezone: "Australia/Melbourne", keywords: ["AEST", "AEDT", "Victoria", "VIC"] },
  { city: "Brisbane", country: "Australia", region: "Oceania", timezone: "Australia/Brisbane", keywords: ["AEST", "Queensland", "QLD"] },
  { city: "Perth", country: "Australia", region: "Oceania", timezone: "Australia/Perth", keywords: ["AWST", "Western Australia", "WA"] },
  { city: "Adelaide", country: "Australia", region: "Oceania", timezone: "Australia/Adelaide", keywords: ["ACST", "ACDT", "South Australia", "SA"] },
  { city: "Auckland", country: "New Zealand", region: "Oceania", timezone: "Pacific/Auckland", keywords: ["NZST", "NZDT", "NZ"] },
  { city: "Wellington", country: "New Zealand", region: "Oceania", timezone: "Pacific/Auckland", keywords: ["NZST", "NZDT", "NZ"] },
  { city: "Port Moresby", country: "Papua New Guinea", region: "Oceania", timezone: "Pacific/Port_Moresby", keywords: ["PGT", "PNG"] },

  // Atlantic
  { city: "Azores", country: "Portugal", region: "Atlantic", timezone: "Atlantic/Azores", keywords: ["AZOT", "AZOST"] },
  { city: "Cape Verde", country: "Cape Verde", region: "Atlantic", timezone: "Atlantic/Cape_Verde", keywords: ["CVT", "Cabo Verde"] },

  // Pacific
  { city: "Suva", country: "Fiji", region: "Pacific", timezone: "Pacific/Fiji", keywords: ["FJT"] },
  { city: "Samoa", country: "Samoa", region: "Pacific", timezone: "Pacific/Apia", keywords: ["WST", "Apia"] },
  { city: "Guam", country: "United States", region: "Pacific", timezone: "Pacific/Guam", keywords: ["ChST", "Chamorro"] },
  { city: "Tahiti", country: "French Polynesia", region: "Pacific", timezone: "Pacific/Tahiti", keywords: ["TAHT", "Papeete"] },
  { city: "Honiara", country: "Solomon Islands", region: "Pacific", timezone: "Pacific/Guadalcanal", keywords: ["SBT"] },
  { city: "Port Vila", country: "Vanuatu", region: "Pacific", timezone: "Pacific/Efate", keywords: ["VUT"] },
  { city: "Nouméa", country: "New Caledonia", region: "Pacific", timezone: "Pacific/Noumea", keywords: ["NCT", "Noumea"] },
  { city: "Nuku'alofa", country: "Tonga", region: "Pacific", timezone: "Pacific/Tongatapu", keywords: ["TOT"] },
  { city: "Tarawa", country: "Kiribati", region: "Pacific", timezone: "Pacific/Tarawa", keywords: ["GILT"] },
  { city: "Funafuti", country: "Tuvalu", region: "Pacific", timezone: "Pacific/Funafuti", keywords: ["TVT"] },
  { city: "Majuro", country: "Marshall Islands", region: "Pacific", timezone: "Pacific/Majuro", keywords: ["MHT"] },
  { city: "Palikir", country: "Micronesia", region: "Pacific", timezone: "Pacific/Pohnpei", keywords: ["PONT", "FSM"] },
  { city: "Ngerulmud", country: "Palau", region: "Pacific", timezone: "Pacific/Palau", keywords: ["PWT"] },
  { city: "Yaren", country: "Nauru", region: "Pacific", timezone: "Pacific/Nauru", keywords: ["NRT"] },
  { city: "Avarua", country: "Cook Islands", region: "Pacific", timezone: "Pacific/Rarotonga", keywords: ["CKT"] },
  { city: "Alofi", country: "Niue", region: "Pacific", timezone: "Pacific/Niue", keywords: ["NUT"] },
  { city: "Pago Pago", country: "American Samoa", region: "Pacific", timezone: "Pacific/Pago_Pago", keywords: ["SST"] },
  { city: "Saipan", country: "Northern Mariana Islands", region: "Pacific", timezone: "Pacific/Guam", keywords: ["ChST", "CNMI"] },
];
